// Code generated by goctl. DO NOT EDIT.
package types

type ArticleReq struct {
	Title  string `json:"title"`
	Link   string `json:"link"`
	Poster string `json:"poster"`
	Time   string `json:"time"`
	Votes  int    `json:"votes"`
}

type ArticleResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
