// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	friend "github.com/gnh123/redis-action-practice/first/internal/handler/friend"
	"github.com/gnh123/redis-action-practice/first/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/first/article",
				Handler: friend.CreateArticleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/first/v1"),
	)
}
